server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/graduation?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      nilbrains:
        zero: DEBUG
# 路径
nil.image.save-path: D:\WeCoding\graduation\images
nil.image.max-size: 2097152
